# Generated by Django 3.2.11 on 2022-05-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraphQl', '0002_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='label',
            field=models.CharField(default=True, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
