# Generated by Django 3.2.11 on 2022-05-19 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GraphQl', '0005_rename_description_issue_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='label',
        ),
    ]
