# Generated by Django 3.2.11 on 2022-05-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GraphQl', '0006_remove_issue_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='reporter',
        ),
    ]
