# Generated by Django 3.2.11 on 2022-05-19 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GraphQl', '0007_auto_20220519_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_assigne', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='reporter',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='reporter_assigne', to='auth.user'),
            preserve_default=False,
        ),
    ]
