# Generated by Django 3.2.11 on 2022-05-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraphQl', '0010_auto_20220520_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowtype',
            name='states',
            field=models.ManyToManyField(blank=True, null=True, related_name='states', to='GraphQl.State'),
        ),
    ]
